# Generated by Django 3.2.9 on 2021-11-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblocked',
            options={'ordering': ['-blocked'], 'verbose_name_plural': 'Users Blocking System'},
        ),
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-start_follow'], 'verbose_name_plural': 'Users Following System'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
