# Generated by Django 3.2.9 on 2021-11-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211126_0228'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('user', 'followed_user'), name='unique_followers'),
        ),
    ]
