# Generated by Django 3.2.9 on 2021-11-29 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('content_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=15)),
                ('external_website', models.URLField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('content_src', models.ImageField(upload_to='pins/')),
                ('share_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PinSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.pin')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.section')),
            ],
        ),
        migrations.CreateModel(
            name='PinNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.note')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.pin')),
            ],
        ),
        migrations.CreateModel(
            name='PinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.category')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.pin')),
            ],
        ),
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.ManyToManyField(through='pin.PinCategory', to='pin.Category'),
        ),
        migrations.AddField(
            model_name='pin',
            name='note',
            field=models.ManyToManyField(through='pin.PinNote', to='pin.Note'),
        ),
        migrations.AddField(
            model_name='pin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pin',
            name='section',
            field=models.ManyToManyField(through='pin.PinSection', to='pin.Section'),
        ),
    ]
