# Generated by Django 3.2.9 on 2021-11-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('content_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=15)),
                ('external_website', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(max_length=500)),
                ('content_src', models.URLField()),
                ('share_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PinNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.note')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.pin')),
            ],
        ),
        migrations.AddField(
            model_name='pin',
            name='PinCategory',
            field=models.ManyToManyField(to='pin.PinCategory'),
        ),
        migrations.AddField(
            model_name='pin',
            name='PinSections',
            field=models.ManyToManyField(to='pin.Section'),
        ),
        migrations.AddField(
            model_name='pin',
            name='note',
            field=models.ManyToManyField(through='pin.PinNote', to='pin.Note'),
        ),
    ]
