# Generated by Django 3.2.9 on 2021-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('content_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=15)),
                ('external_website', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(max_length=500)),
                ('content_src', models.URLField()),
                ('share_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=15)),
                ('PinCategory', models.ManyToManyField(to='pin.PinCategory')),
                ('PinSections', models.ManyToManyField(to='pin.Section')),
                ('notes', models.ManyToManyField(to='pin.Note')),
            ],
        ),
    ]
