# Generated by Django 3.2.9 on 2021-11-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='notes',
            new_name='note',
        ),
    ]
