# Generated by Django 3.2.9 on 2021-11-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincategory',
            old_name='Category',
            new_name='category',
        ),
    ]
