# Generated by Django 3.2.9 on 2021-11-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_rename_category_pincategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinsection',
            old_name='Section',
            new_name='section',
        ),
    ]
