# Generated by Django 3.2.9 on 2021-11-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(blank=True, null=True, to='pin.Pin'),
        ),
    ]
