# Generated by Django 3.2.9 on 2021-11-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='boards',
            field=models.ManyToManyField(to='board.Board'),
        ),
    ]
