# Generated by Django 3.2.9 on 2021-11-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='board_covers'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
