# Generated by Django 3.2.9 on 2021-11-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211126_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='boards',
        ),
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='board.Collaborator'),
        ),
    ]
