# Generated by Django 3.2.9 on 2021-11-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20211126_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='ckeck_list',
        ),
        migrations.AddField(
            model_name='note',
            name='ckecklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
