# Generated by Django 3.2.9 on 2021-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20211125_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, to='board.Collaborator'),
        ),
    ]
