# Generated by Django 3.2.9 on 2021-11-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211123_2000'),
        ('board', '0004_auto_20211126_0129'),
    ]

    operations = [
    ]
